#######################################################################################
# Book settings
title : Machine Learning Engineer
author: Emmanuel Decena
logo: 'images/neural.png'

# Information about where the book exists on the web
#description: >-
#  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : -1
#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  favicon                     : 'images/favicon.png'
  extra_navbar                : ""
  #google_analytics_id       : ""
  #use_repository_button: true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/emmandecena/jupyterbook
  path_to_book                : "book"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
