#######################################################################################
# Book settings
title : Analytics & Insights in Electricity Markets
author: Emmanuel Decena
logo: 'images/neural.png'

# Information about where the book exists on the web
#description: >-
#  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : -1
  exclude_patterns            : [draft*]
#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  favicon                     : 'images/favicon.png'
  extra_navbar                : ""
  google_analytics_id         : "UA-175171081-1"
  #use_repository_button: true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/emmandecena/jupyterbook
  path_to_book                : "book"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
#######################################################################################
# For Plotly
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_extra_path: ['cv']
#######################################################################################
# For Images
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
#######################################################################################
# Do not build not in TOC
only_build_toc_files: true
