#######################################################################################
# Book settings
title : Data Scientist | Energy
author: Emmanuel Decena
logo: 'images/neural.png'

# Information about where the book exists on the web
#description: >-
#  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

execute:
  timeout: -1
#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/emmandecena/jupyterbook
  path_to_book                : "book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
